/* global alertify */
//*************      JQUERY PARA TRADUCIR EL MODULO DEL ENTRENADOR A INGLES     *****************
$('#traducirEntrenadorIngles').click(function () {    
    alertify.success('<h5 style="color: #fff;font-size: 1.3em">Translated into english</h5>');
    $('#mensajeModal').html('Do you have any questions, complaints, complaints, or suggestions, write to us ...');
    $('#cerrarModal').html('Close');
    $('#enviarModal').html('Submit');
    $('#cerrarSesionAviso').html('<i class="fas fa-power-off"></i> Logout');
    $('#exampleModalLabel').html('Ready to go?');
    $('#selecionCerrarSesion').html('Select "Logout" below if you are ready to end your current session.');
    $('#CancelarModal').html('Cancel');
    $('#cerrarSesoin').html('Logout');
    $('#consultarJugador').html('Consult player');
    $('#Solicitarprestamo').html('Apply for a loan');
    $('#Descripciorendimiento').html('Performance test description');
    $('#bienbenidos').html('WELCOME TO THE SPORTS PERFORMANCE SYSTEM');
    $('#enviarmensajeee').html('Send mail');
    $('#enviarcorreoooooooo').html('Send mail...');
    $('#paraCorreo').html('For:');
    $('#asuntoCorreo').html('Affair:');
    $('#adjuntarArchivocorreo').html('Attach file');
    $('#mensajecorreo').html('Message');
    $('.btnEnviarCorreo').html('Submit');
    $('#btn_CAncelarCorreo').html('Cancel');
    
//solicitar préstamo
    $('#SolicitarprestamoPrstamo').html('Apply for a loan.');
    $('#AgregarnuevoPrestamo').html('Add new');
    $('#Idprestamo').html('Id loan');
    $('#CantidadPrestamo').html('Quantity');
    $('#Nombreimplemento').html('Implement name');
    $('#Fechaprestamo').html('Loan date');
    $('#Horadevolucion').html('Return time');
    $('#Editar').html('Edit');
    $('#Eliminar').html('Remove');
    $('#SolicitarprestamoRe').html('Apply for a loan.');
    $('#cantidadprestamoRe').html('Quantity');
    $('#mnombreImplementoRe').html('Implement name');
    $('#frchaPrestamoRe').html('Loan date');
    $('#horaPrestamoRe').html('Return time');
    $('#limipiarprestamoRe').html('Clean');
    $('#cancelarprestamoRe').html('Cancel');
    $('.agregarPrestamoRe').html('Add');
    $('#Modificarprestamo').html('Modify loan.');
    $('#idMo').html('ID');
    $('#cantidadPrestamoMo').html('Quantity');
    $('#nombreInpelementoMo').html('Implement name');
    $('#fechaprstamoMo').html('Loan date');
    $('#horaDevolucionMo').html('Return time');
    $('#cancelarMo').html('Cancel');
    $('#actuañizarPrestamoMo').html('Update');
    
//consultar jugador    
    $('#consultarJugadorJugador').html('Consult player');
    $('#buscador').html('Seeker...');
    $('#seleccionejugador').html('Select a player');
    $('#verPerfilJugador').html('See player profile');
    
//VALORACION TEST    
    $('#perfiljugadortest').html('Player profile');
    $('#RegistrarTest').html('Register test.');
    $('#RegistrarnuevoTest').html('Register new Test');
    $('#idvaloracion').html('Id rating');
    $('#nombretestest').html('Test name');
    $('#resultadotesttest').html('Result');
//    $('#nombretestest').html('Logout');
    $('#fechatest').html('Date');
    $('#comentarioTest').html('Commentary');
    $('#codigojugadortest').html('Player code');
    $('#editarTest').html('Edit');
    $('#eliminarTest').html('Remove');
    $('#nuevtestre').html('New test');
    $('#nombretestRe').html('Test name');
    $('#testvelocidadRe').html('Speed Test');
    $('#Testfuerzare').html('Strength test');
    $('#TestResistenciare').html('Resistance Test');
    $('#TestCoordinacionre').html('Coordination Test');
    $('#TestPasere').html('Test Pass');
    $('#TestConduccionre').html('Driving Test');
    $('#TestCabeceore').html('Pitch Test');
    $('#TestTirore').html('Shot test');
    $('#iresultadoTestmo').html('Result');
    $('#fechatestRe').html('Date');
    $('#codigojugadorre').html('Player code');
    $('#comentariotestre').html('Commentary');
    $('#limiartestRe').html('Clean');
    $('#cancelartestre').html('Cancel');
    $('.agregartestre').html('Add');
    $('#modificartestmo').html('Modificar test.');
    $('#nombretestMo').html('Name test');
    $('#testvelocidadMo').html('Speed Test');
    $('#TestfuerzaMo').html('Strength test');
    $('#TestResistenciaMo').html('Resistance Test');
    $('#TestCoordinacionMo').html('Coordination Test');
    $('#TestPaseMo').html('Test Pass');
    $('#TestConduccionMo').html('Driving Test');
    $('#TestCabeceoMo').html('Pitch Test');
    $('#TestTiroMo').html('Shot test');
    $('#fechaTestMo').html('Date');
    $('#resultadotestmo').html('Result');
    $('#codigojugadorTestmo').html('Player code');
    $('#comentariotestmo').html('Commentary');
    $('#cancelartestmo').html('Cancel');
    $('.actualizartestmo').html('Update');
    
 //RENDIMIENTO CAMPEONATO   
    $('#perfiljugadoRendi').html('Player profile');
    $('#registrarrendimientocamp').html('Record Performance in the championship..');
    $('#agregarnuevo').html('Add new');
    $('#idRendimiento').html('Id performance');
    $('#Goles').html('Goals');
    $('#Asistencia').html('Assistance');
    $('#tiempoJugado').html('Time played');
    $('#partidoss').html('Matches played');
    $('#targetasrojas').html('Red cards');
    $('#tarjetasamarillas').html('Yellow cards');
    $('#codigojugadorRendi').html('Player code');
    $('#comentariorendi').html('Commentary');
    $('#editarrendi').html('Edit');
    $('#elimianrrendi').html('Remove');
    $('#nuevorendimientorendire').html('New performance.');
    $('#golesrendire').html('Goals');
    $('#asistenciaremndire').html('Assistance');
    $('#tiempojugadorendire').html('Time played');
    $('#partidosjugadosrendire').html('Matches played');
    $('#tarjetasrpojasrendire').html('Red cards');
    $('#tarjetasAmarillas').html('Yellow cards');
    $('#codigojugadorrendire').html('Player code');
    $('#comentariorendire').html('Commentary');
    $('#limpiarrenidre').html('Clean');
    $('#cancelarrendire').html('Cancel');
    $('.agregarrendimire').html('Add');
    $('#modificarrendimientomo').html('Modify Performance ');
    $('#golesmo').html('Goals');
    $('#asistencaimo').html('Assistance');
    $('#tiempojugadormo').html('Time played');
    $('#partidosjugadosmo').html('Matches played');
    $('#tarjhetasrojasmo').html('Red cards');
    $('#tarjetasamarillasmo').html('Yellow cards');
    $('#codigojugadoreno').html('Player code');
    $('#comentariomo').html('Commentary');
    $('#cancelarrrmo').html('Cancel');
    $('.actualizarrrmo').html('Update');
    
 //CONSULTAR PERFIL DEL JUGADOR   
    $('.PerfilJugadorrr').html('Player profile');
    $('.DatosPersonales').html('Personal information');
    $('.IdentificacionPe').html('ID');
    $('.CodigoPe').html('Code');
    $('.TelefonoPe').html('Phone');
    $('.CelularPer').html('Mobile');
    $('.CorreoPer').html('Email');
    $('.DireccionPer').html('Direction');
    $('.DatosDeportivosPree').html('Sports Data');
    $('.Categoriaperr').html('Category');
    $('.AlturaPre').html('Height');
    $('.edadpre').html('Age');
    $('.pesopre').html('Weight');
    $('.Numerodorsalpre').html('Dorsal number');
    $('.Piedominantepre').html('Dominant foot');
    $('.TestDeljugadorprere').html('Player Test');
    $('.Rendimientocampeonatoasasasa').html('Championship Performance');
    $('.golesrenpre').html('Goals');
    $('.asistenciarenpre').html('Assists');
    $('.tiempojurenpre').html('Played Time');
    $('.partidosjugadosrenpre').html('Matches played');
    $('.tarjetasrojasrenpre').html('Red cards');
    $('.tarjetasamarillasrenpre').html('Yellow cards');
    $('.Reportedeljugadorsads').html('Player Report');
    
// DESCRIPCION TEST    
    $('#consultedescripciontest').html('See the description of the tests.');
    $('#iddescripcion').html('Id description test');
    $('#nombretestdescripcion').html('Test name');
    $('#descripciontesttestss').html('Description');
    $('#TestvelocidadDes').html('Speed test');
    $('#TestfuerzaDes').html('Strength test');
    $('#Testresistenciades').html('Resistance test');
    $('#Testcoordinaciondes').html('Coordination test');
    $('#Testpasedes').html('Test pass');
    $('#Tescabeceodes').html('Pitch Test');
    $('#Testconduccióndes').html('Driving Test');
    $('#Testtirodes').html('Shot test');
    
    $('#testss').html('Logout');
    $('#testss').html('Logout');
    $('#testss').html('Logout');
    $('#testss').html('Logout');
    $('#testss').html('Logout');
    $('#testss').html('Logout');
    $('#testss').html('Logout');
    $('#testss').html('Logout');
    $('#testss').html('Logout');
    
});

//***********************        JQUERY PARA TRADUCIR EL MODULO DEL ENTRENADOR A ESPAÑOL          *************************************************

$('#traducirEntrenadorEspañol').click(function () {
    alertify.success('<h5 style="color: #fff;font-size: 1.3em">Traducido a español</h5>');
    $('#mensajeModal').html('Tienes alguna pregunta, queja, reclamo, o sugerencia, escríbenos...');
    $('#cerrarModal').html('Cerrar');
    $('#enviarModal').html('Enviar');
    $('#cerrarSesionAviso').html('<i class="fas fa-power-off"></i> Cerrar sesión');
    $('#exampleModalLabel').html('¿Listo para salir?');
    $('#selecionCerrarSesion').html('Seleccione "Cerrar sesión" a continuación si está listo para finalizar su sesión actual. ');
    $('#CancelarModal').html('Cancelar');
    $('#cerrarSesoin').html('Cerrar sesión');
    $('#consultarJugador').html('Consultar jugador');
    $('#Solicitarprestamo').html('Solicitar préstamo');
    $('#Descripciorendimiento').html('Descripción test de rendimiento');
    $('#bienbenidos').html('BIENVENIDO AL MÓDULO DE RENDIMIENTO DEPORTIVO');
    $('#enviarmensajeee').html('Enviar correo');
    $('#enviarcorreoooooooo').html('Enviar correo...');
    $('#paraCorreo').html('Para:');
    $('#asuntoCorreo').html('Asunto:');
    $('#adjuntarArchivocorreo').html('Adjuntar archivo');
    $('#mensajecorreo').html('Mensaje');
    $('.btnEnviarCorreo').html('Enviar');
    $('#btn_CAncelarCorreo').html('Cancelar');
    
//solicitar préstamo
    $('#SolicitarprestamoPrstamo').html('Solicitar préstamo.');
    $('#AgregarnuevoPrestamo').html('Agregar nuevo');
    $('#Idprestamo').html('Id préstamo');
    $('#CantidadPrestamo').html('Cantidad');
    $('#Nombreimplemento').html('Nombre implemento');
    $('#Fechaprestamo').html('Fecha préstamo');
    $('#Horadevolucion').html('Hora devolucion');
    $('#Editar').html('Editar');
    $('#Eliminar').html('Eliminar');
    $('#SolicitarprestamoRe').html('Solicitar préstamo.');
    $('#cantidadprestamoRe').html('Cantidad');
    $('#mnombreImplementoRe').html('Nombre implemento');
    $('#frchaPrestamoRe').html('Fecha préstamo');
    $('#horaPrestamoRe').html('Hora devolucion');
    $('#limipiarprestamoRe').html('Limpiar');
    $('#cancelarprestamoRe').html('Cancelar');
    $('.agregarPrestamoRe').html('Agregar');
    $('#Modificarprestamo').html('Modificar préstamo.');
    $('#idMo').html('Id');
    $('#cantidadPrestamoMo').html('Cantidad');
    $('#nombreInpelementoMo').html('Nombre implemento');
    $('#fechaprstamoMo').html('Fecha préstamo');
    $('#horaDevolucionMo').html('Hora devolución');
    $('#cancelarMo').html('Cancelar');
    $('#actuañizarPrestamoMo').html('Actualizar');
    
//consultar jugador    
    $('#consultarJugadorJugador').html('Consultar jugador');
    $('#buscador').html('Buscador...');
    $('#seleccionejugador').html('Seleccione un jugador');
    $('#verPerfilJugador').html('Ver perfil jugador');
    
//VALORACION TEST    
    $('#perfiljugadortest').html('Perfil jugador');
    $('#RegistrarTest').html('Registrar test.');
    $('#RegistrarnuevoTest').html('Registrar nuevo Test');
    $('#idvaloracion').html('Id valoración');
    $('#nombretestest').html('Nombre test');
    $('#resultadotesttest').html('Resultado');
    $('#fechatest').html('Fecha');
    $('#comentarioTest').html('Comentario');
    $('#codigojugadortest').html('Código jugador');
    $('#editarTest').html('Editar');
    $('#eliminarTest').html('Eliminar');
    $('#nuevtestre').html('Nuevo test');
    $('#nombretestRe').html('Nombre test');
    $('#testvelocidadRe').html('Test Velocidad ');
    $('#Testfuerzare').html('Test fuerza');
    $('#TestResistenciare').html('Test Resistencia ');
    $('#TestCoordinacionre').html('Test Coordinación');
    $('#TestPasere').html('Test Pase');
    $('#TestConduccionre').html('Test Conducción ');
    $('#TestCabeceore').html('Test Cabeceo ');
    $('#TestTirore').html('Test Tiro');
    $('#iresultadoTestmo').html('Resultado');
    $('#fechatestRe').html('Fecha');
    $('#codigojugadorre').html('Código jugador');
    $('#comentariotestre').html('Comentario');
    $('#limiartestRe').html('Limpiar');
    $('#cancelartestre').html('Cancelar');
    $('.agregartestre').html('Agregar');
    $('#modificartestmo').html('Modificar test.');
    $('#nombretestMo').html('Modificar test.');
    $('#testvelocidadMo').html('Test Velocidad ');
    $('#TestfuerzaMo').html('Test fuerza');
    $('#TestResistenciaMo').html('Test Resistencia ');
    $('#TestCoordinacionMo').html('Test Coordinación');
    $('#TestPaseMo').html('Test Pase');
    $('#TestConduccionMo').html('Test Conducción ');
    $('#TestCabeceoMo').html('Test Cabeceo ');
    $('#TestTiroMo').html('Test Tiro');
    $('#fechaTestMo').html('Fecha');
    $('#resultadotestmo').html('Resultado');
    $('#codigojugadorTestmo').html('Código jugador');
    $('#comentariotestmo').html('Comentario');
    $('#cancelartestmo').html('Cancelar');
    $('.actualizartestmo').html('Actualizar');
    
//RENDIMIENTO CAMPEONATO   
    $('#perfiljugadoRendi').html('Perfil jugador');
    $('#registrarrendimientocamp').html('Registra Rendimiento en el campeonato.');
    $('#agregarnuevo').html('Agregar nuevo');
    $('#idRendimiento').html('id Rendimiento');
    $('#Goles').html('Goles');
    $('#Asistencia').html('Asistencia');
    $('#tiempoJugado').html('Tiempo jugado');
    $('#partidoss').html('Partidos jugados');
    $('#targetasrojas').html('Tarjetas rojas');
    $('#tarjetasamarillas').html('Tarjetas amarillas ');
    $('#codigojugadorRendi').html('Código jugador');
    $('#comentariorendi').html('Comentario');
    $('#editarrendi').html('Editar');
    $('#elimianrrendi').html('Eliminar');
    $('#nuevorendimientorendire').html('Nuevo rendimiento.');
    $('#golesrendire').html('Goles');
    $('#asistenciaremndire').html('Asistencia');
    $('#tiempojugadorendire').html('Tiempo jugado');
    $('#partidosjugadosrendire').html('Partidos jugados');
    $('#tarjetasrpojasrendire').html('Tarjetas rojas');
    $('#tarjetasAmarillas').html('Tarjetas amarillas ');
    $('#codigojugadorrendire').html('Código jugador');
    $('#comentariorendire').html('Comentario');
    $('#limpiarrenidre').html('Limpiar');
    $('#cancelarrendire').html('CAncelar');
    $('.agregarrendimire').html('Agregar');
    $('#modificarrendimientomo').html('Modificar rendimiento');
    $('#golesmo').html('Goles');
    $('#asistencaimo').html('Asistencia');
    $('#tiempojugadormo').html('Tiempo jugado');
    $('#partidosjugadosmo').html('Partidos jugados');
    $('#tarjhetasrojasmo').html('Tarjetas rojas');
    $('#tarjetasamarillasmo').html('Tarjetas amarillas');
    $('#codigojugadoreno').html('Código jugador');
    $('#comentariomo').html('Comentario');
    $('#cancelarrrmo').html('cancelar');
    $('.actualizarrrmo').html('Actualizar');
    
//CONSULTAR PERFIL DEL JUGADOR   
    $('.PerfilJugadorrr').html('Perfil del jugador');
    $('.DatosPersonales').html('Datos Personales ');
    $('.IdentificacionPe').html('Identificación');
    $('.CodigoPe').html('Código');
    $('.TelefonoPe').html('Teléfono');
    $('.CelularPer').html('Celular ');
    $('.CorreoPer').html('Correo');
    $('.DireccionPer').html('Dirección');
    $('.DatosDeportivosPree').html('Datos Deportivos');
    $('.Categoriaperr').html('Categoría ');
    $('.AlturaPre').html('Altura');
    $('.edadpre').html('Edad');
    $('.pesopre').html('Peso');
    $('.Numerodorsalpre').html('Numero dorsal');
    $('.Piedominantepre').html('Pie dominante');
    $('.TestDeljugadorprere').html('Test Del jugador ');
    $('.Rendimientocampeonatoasasasa').html('Rendimiento campeonato ');
    $('.golesrenpre').html('Goles');
    $('.asistenciarenpre').html('Asistencia');
    $('.tiempojurenpre').html('Tiempo Jugado');
    $('.partidosjugadosrenpre').html('Partidos jugados');
    $('.tarjetasrojasrenpre').html('Tarjetas rojas');
    $('.tarjetasamarillasrenpre').html('Tarjetas Amarillas');
    $('.Reportedeljugadorsads').html('Reporte del jugador');
    
// DEWSCRIPCION TEST    
    $('#consultedescripciontest').html('Consulte la descripción de los test.');
    $('#iddescripcion').html('Id descripción test');
    $('#nombretestdescripcion').html('Nombre test');
    $('#descripciontesttestss').html('Descripción');
    $('#TestvelocidadDes').html('Test velocidad');
    $('#TestfuerzaDes').html('Test fuerza');
    $('#Testresistenciades').html('Test resistencia');
    $('#Testcoordinaciondes').html('Test coordinación ');
    $('#Testpasedes').html('Test pase');
    $('#Tescabeceodes').html('Test cabeceo');
    $('#Testconduccióndes').html('Test conducción');
    $('#Testtirodes').html('Test tiro');
});


